name: Build, create a release and deploy the PDF to GitHub pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci-checks:
    uses: ./.github/workflows/partial-ci-checks.yml
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    needs: ci-checks
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker container and generate PDF
        run: |
          docker build --target production -t pdf-generator .
          docker run --rm -v "$(pwd)/public:/app/public" pdf-generator

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: public

  release:
    runs-on: ubuntu-latest
    needs: [ci-checks, build]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.ci-checks.outputs.version }}
          name: Release v${{ needs.ci-checks.outputs.version }}
          files: public/profile.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
